#!/bin/bash
printf "%s\n" "$((5#$(echo "$WATER" | tr 'water' '01234'))) + $((5#$(echo "$STIR" | tr 'stir.' '01234')))" | bc | printf "%s\n" "$(cat -)" "obase=bestchol; $(cat -)" | tr '01234567' 'bestchol'
