#!/usr/bin/env bash
# Bash script that displays the PID and process name of processes containing the word "bash"

my_pid=$$

name=$(pgrep -af bash)

echo "$name" | while read -r line; do
  pid=$(echo "$line" | awk '{print $1}')
  process_name=$(echo "$line" | awk '{print $2}')
  echo "$pid $process_name"
done | grep bash | grep -v "$my_pid"
