#!/usr/bin/env bash
# This script displays "Best School" 10 times, and for the 9th iteration, displays "Hi" on a new line

i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
    fi
    ((i++))
done
