#!/usr/bin/env bash
# This script loops from 1 to 10 and displays different messages based on the iteration number

i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
    	fi
    ((i++))
done
