#!/usr/bin/env bash

file_path="school"

if [ -e "$file_path" ]; then
    echo "$file_path file exists"
    
    if [ -s "$file_path" ]; then
        echo "$file_path is not empty"
    else
        echo "$file_path is empty"
    fi

    if [ -f "$file_path" ]; then
        echo "$file_path is a regular file"
    fi
else
    echo "$file_path file does not exist"
fi
